name: Ruby/CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: install PostgreSQL client
      run: sudo apt-get install libpq-dev
    - uses: actions/cache@v1
      id: cache
      with:
        path: bundle/
        key: ${{ runner.os }}-${{ hashFiles('Gemfile.lock') }}
    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        gem install bundler
        bundle install --standalone=test,development --jobs 4 --retry 3
    - name: Run danger
      run: |
        bundle exec danger --verbose
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Run rspec
      run: |
        bundle exec rspec
