name: Danger

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: danger/danger
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
